#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
%define keepstatic 1
Name     : libzmq
Version  : 4.3.3
Release  : 9
URL      : https://github.com/zeromq/libzmq/releases/download/v4.3.3/zeromq-4.3.3.tar.gz
Source0  : https://github.com/zeromq/libzmq/releases/download/v4.3.3/zeromq-4.3.3.tar.gz
Summary  : 0MQ c++ library
Group    : Development/Tools
License  : BSD-2-Clause GPL-3.0 LGPL-3.0 MIT
Requires: libzmq-bin = %{version}-%{release}
Requires: libzmq-lib = %{version}-%{release}
Requires: libzmq-license = %{version}-%{release}
Requires: libzmq-man = %{version}-%{release}
BuildRequires : asciidoc
BuildRequires : buildreq-cmake
BuildRequires : pkgconfig(gnutls)
BuildRequires : pkgconfig(krb5-gssapi)
BuildRequires : pkgconfig(libunwind)
BuildRequires : pkgconfig(nss)
BuildRequires : sed
BuildRequires : valgrind
BuildRequires : xmlto

%description
This directory holds build tools, i.e. tools we use to build the current
code tree. Packaging tools (which take released tarballs or github code
repos) should go into /packaging.

%package bin
Summary: bin components for the libzmq package.
Group: Binaries
Requires: libzmq-license = %{version}-%{release}

%description bin
bin components for the libzmq package.


%package dev
Summary: dev components for the libzmq package.
Group: Development
Requires: libzmq-lib = %{version}-%{release}
Requires: libzmq-bin = %{version}-%{release}
Provides: libzmq-devel = %{version}-%{release}
Requires: libzmq = %{version}-%{release}

%description dev
dev components for the libzmq package.


%package lib
Summary: lib components for the libzmq package.
Group: Libraries
Requires: libzmq-license = %{version}-%{release}

%description lib
lib components for the libzmq package.


%package license
Summary: license components for the libzmq package.
Group: Default

%description license
license components for the libzmq package.


%package man
Summary: man components for the libzmq package.
Group: Default

%description man
man components for the libzmq package.


%package staticdev
Summary: staticdev components for the libzmq package.
Group: Default
Requires: libzmq-dev = %{version}-%{release}

%description staticdev
staticdev components for the libzmq package.


%prep
%setup -q -n zeromq-4.3.3
cd %{_builddir}/zeromq-4.3.3

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1602609315
export GCC_IGNORE_WERROR=1
export CFLAGS="$CFLAGS -fno-lto -fstack-protector-strong -mzero-caller-saved-regs=used "
export FCFLAGS="$FFLAGS -fno-lto -fstack-protector-strong -mzero-caller-saved-regs=used "
export FFLAGS="$FFLAGS -fno-lto -fstack-protector-strong -mzero-caller-saved-regs=used "
export CXXFLAGS="$CXXFLAGS -fno-lto -fstack-protector-strong -mzero-caller-saved-regs=used "
%configure  --without-pgm \
--disable-libbsd
make  %{?_smp_mflags}

%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make %{?_smp_mflags} check || :

%install
export SOURCE_DATE_EPOCH=1602609315
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/libzmq
cp %{_builddir}/zeromq-4.3.3/COPYING %{buildroot}/usr/share/package-licenses/libzmq/99b1a5c7351fd39a26db3b560ce91eec4a3aca3d
cp %{_builddir}/zeromq-4.3.3/COPYING.LESSER %{buildroot}/usr/share/package-licenses/libzmq/cd024bd665e7b8244ee020856b359e3d7babc454
cp %{_builddir}/zeromq-4.3.3/external/unity/license.txt %{buildroot}/usr/share/package-licenses/libzmq/82d0bcdf2087a772a9517374e2df993d85fb447e
cp %{_builddir}/zeromq-4.3.3/external/wepoll/license.txt %{buildroot}/usr/share/package-licenses/libzmq/0cf031c01628cf0ee33ed398038238a76ebbd1b7
%make_install

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/curve_keygen

%files dev
%defattr(-,root,root,-)
/usr/include/zmq.h
/usr/include/zmq_utils.h
/usr/lib64/libzmq.so
/usr/lib64/pkgconfig/libzmq.pc
/usr/share/man/man3/zmq_atomic_counter_dec.3
/usr/share/man/man3/zmq_atomic_counter_destroy.3
/usr/share/man/man3/zmq_atomic_counter_inc.3
/usr/share/man/man3/zmq_atomic_counter_new.3
/usr/share/man/man3/zmq_atomic_counter_set.3
/usr/share/man/man3/zmq_atomic_counter_value.3
/usr/share/man/man3/zmq_bind.3
/usr/share/man/man3/zmq_close.3
/usr/share/man/man3/zmq_connect.3
/usr/share/man/man3/zmq_connect_peer.3
/usr/share/man/man3/zmq_ctx_get.3
/usr/share/man/man3/zmq_ctx_new.3
/usr/share/man/man3/zmq_ctx_set.3
/usr/share/man/man3/zmq_ctx_shutdown.3
/usr/share/man/man3/zmq_ctx_term.3
/usr/share/man/man3/zmq_curve_keypair.3
/usr/share/man/man3/zmq_curve_public.3
/usr/share/man/man3/zmq_disconnect.3
/usr/share/man/man3/zmq_errno.3
/usr/share/man/man3/zmq_getsockopt.3
/usr/share/man/man3/zmq_has.3
/usr/share/man/man3/zmq_msg_close.3
/usr/share/man/man3/zmq_msg_copy.3
/usr/share/man/man3/zmq_msg_data.3
/usr/share/man/man3/zmq_msg_get.3
/usr/share/man/man3/zmq_msg_gets.3
/usr/share/man/man3/zmq_msg_init.3
/usr/share/man/man3/zmq_msg_init_buffer.3
/usr/share/man/man3/zmq_msg_init_data.3
/usr/share/man/man3/zmq_msg_init_size.3
/usr/share/man/man3/zmq_msg_more.3
/usr/share/man/man3/zmq_msg_move.3
/usr/share/man/man3/zmq_msg_recv.3
/usr/share/man/man3/zmq_msg_routing_id.3
/usr/share/man/man3/zmq_msg_send.3
/usr/share/man/man3/zmq_msg_set.3
/usr/share/man/man3/zmq_msg_set_routing_id.3
/usr/share/man/man3/zmq_msg_size.3
/usr/share/man/man3/zmq_poll.3
/usr/share/man/man3/zmq_poller.3
/usr/share/man/man3/zmq_proxy.3
/usr/share/man/man3/zmq_proxy_steerable.3
/usr/share/man/man3/zmq_recv.3
/usr/share/man/man3/zmq_recvmsg.3
/usr/share/man/man3/zmq_send.3
/usr/share/man/man3/zmq_send_const.3
/usr/share/man/man3/zmq_sendmsg.3
/usr/share/man/man3/zmq_setsockopt.3
/usr/share/man/man3/zmq_socket.3
/usr/share/man/man3/zmq_socket_monitor.3
/usr/share/man/man3/zmq_socket_monitor_versioned.3
/usr/share/man/man3/zmq_strerror.3
/usr/share/man/man3/zmq_timers.3
/usr/share/man/man3/zmq_unbind.3
/usr/share/man/man3/zmq_version.3
/usr/share/man/man3/zmq_z85_decode.3
/usr/share/man/man3/zmq_z85_encode.3

%files lib
%defattr(-,root,root,-)
/usr/lib64/libzmq.so.5
/usr/lib64/libzmq.so.5.2.3

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/libzmq/0cf031c01628cf0ee33ed398038238a76ebbd1b7
/usr/share/package-licenses/libzmq/82d0bcdf2087a772a9517374e2df993d85fb447e
/usr/share/package-licenses/libzmq/99b1a5c7351fd39a26db3b560ce91eec4a3aca3d
/usr/share/package-licenses/libzmq/cd024bd665e7b8244ee020856b359e3d7babc454

%files man
%defattr(0644,root,root,0755)
/usr/share/man/man7/zmq.7
/usr/share/man/man7/zmq_curve.7
/usr/share/man/man7/zmq_gssapi.7
/usr/share/man/man7/zmq_inproc.7
/usr/share/man/man7/zmq_ipc.7
/usr/share/man/man7/zmq_null.7
/usr/share/man/man7/zmq_pgm.7
/usr/share/man/man7/zmq_plain.7
/usr/share/man/man7/zmq_tcp.7
/usr/share/man/man7/zmq_tipc.7
/usr/share/man/man7/zmq_udp.7
/usr/share/man/man7/zmq_vmci.7

%files staticdev
%defattr(-,root,root,-)
/usr/lib64/libzmq.a
