#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: configure
# autospec version: v13
# autospec commit: dc0ff31
#
%define keepstatic 1
Name     : libzmq
Version  : 4.3.5
Release  : 13
URL      : https://github.com/zeromq/libzmq/releases/download/v4.3.5/zeromq-4.3.5.tar.gz
Source0  : https://github.com/zeromq/libzmq/releases/download/v4.3.5/zeromq-4.3.5.tar.gz
Summary  : 0MQ c++ library
Group    : Development/Tools
License  : BSD-2-Clause MIT MPL-2.0-no-copyleft-exception
Requires: libzmq-lib = %{version}-%{release}
Requires: libzmq-license = %{version}-%{release}
Requires: libzmq-man = %{version}-%{release}
BuildRequires : asciidoc
BuildRequires : buildreq-configure
BuildRequires : pkgconfig(gnutls)
BuildRequires : pkgconfig(krb5-gssapi)
BuildRequires : pkgconfig(libunwind)
BuildRequires : pkgconfig(nss)
BuildRequires : sed
BuildRequires : valgrind
BuildRequires : xmlto
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
This directory holds build tools, i.e. tools we use to build the current
code tree. Packaging tools (which take released tarballs or github code
repos) should go into /packaging.

%package dev
Summary: dev components for the libzmq package.
Group: Development
Requires: libzmq-lib = %{version}-%{release}
Provides: libzmq-devel = %{version}-%{release}
Requires: libzmq = %{version}-%{release}

%description dev
dev components for the libzmq package.


%package lib
Summary: lib components for the libzmq package.
Group: Libraries
Requires: libzmq-license = %{version}-%{release}

%description lib
lib components for the libzmq package.


%package license
Summary: license components for the libzmq package.
Group: Default

%description license
license components for the libzmq package.


%package man
Summary: man components for the libzmq package.
Group: Default

%description man
man components for the libzmq package.


%package staticdev
Summary: staticdev components for the libzmq package.
Group: Default
Requires: libzmq-dev = %{version}-%{release}

%description staticdev
staticdev components for the libzmq package.


%prep
%setup -q -n zeromq-4.3.5
cd %{_builddir}/zeromq-4.3.5
pushd ..
cp -a zeromq-4.3.5 buildavx2
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1719973087
export GCC_IGNORE_WERROR=1
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export GOAMD64=v2
%configure  --without-pgm \
--disable-libbsd
make  %{?_smp_mflags}

unset PKG_CONFIG_PATH
pushd ../buildavx2/
GOAMD64=v3
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -march=x86-64-v3 -Wl,-z,x86-64-v3 "
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -march=x86-64-v3 -Wl,-z,x86-64-v3 "
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -march=x86-64-v3 -Wl,-z,x86-64-v3 "
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS -march=x86-64-v3 "
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS -march=x86-64-v3 "
%configure  --without-pgm \
--disable-libbsd
make  %{?_smp_mflags}
popd
%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make %{?_smp_mflags} check || :
cd ../buildavx2;
make %{?_smp_mflags} check || : || :

%install
export GCC_IGNORE_WERROR=1
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export SOURCE_DATE_EPOCH=1719973087
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/libzmq
cp %{_builddir}/zeromq-%{version}/LICENSE %{buildroot}/usr/share/package-licenses/libzmq/d22157abc0fc0b4ae96380c09528e23cf77290a9 || :
cp %{_builddir}/zeromq-%{version}/external/unity/license.txt %{buildroot}/usr/share/package-licenses/libzmq/82d0bcdf2087a772a9517374e2df993d85fb447e || :
cp %{_builddir}/zeromq-%{version}/external/wepoll/license.txt %{buildroot}/usr/share/package-licenses/libzmq/34f3af59f7997f370973f96fdc316677f47a813d || :
export GOAMD64=v2
GOAMD64=v3
pushd ../buildavx2/
%make_install_v3
popd
GOAMD64=v2
%make_install
/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)

%files dev
%defattr(-,root,root,-)
/usr/include/zmq.h
/usr/include/zmq_utils.h
/usr/lib64/libzmq.so
/usr/lib64/pkgconfig/libzmq.pc
/usr/share/man/man3/zmq_atomic_counter_dec.3
/usr/share/man/man3/zmq_atomic_counter_destroy.3
/usr/share/man/man3/zmq_atomic_counter_inc.3
/usr/share/man/man3/zmq_atomic_counter_new.3
/usr/share/man/man3/zmq_atomic_counter_set.3
/usr/share/man/man3/zmq_atomic_counter_value.3
/usr/share/man/man3/zmq_bind.3
/usr/share/man/man3/zmq_close.3
/usr/share/man/man3/zmq_connect.3
/usr/share/man/man3/zmq_connect_peer.3
/usr/share/man/man3/zmq_ctx_get.3
/usr/share/man/man3/zmq_ctx_new.3
/usr/share/man/man3/zmq_ctx_set.3
/usr/share/man/man3/zmq_ctx_shutdown.3
/usr/share/man/man3/zmq_ctx_term.3
/usr/share/man/man3/zmq_curve_keypair.3
/usr/share/man/man3/zmq_curve_public.3
/usr/share/man/man3/zmq_disconnect.3
/usr/share/man/man3/zmq_errno.3
/usr/share/man/man3/zmq_getsockopt.3
/usr/share/man/man3/zmq_has.3
/usr/share/man/man3/zmq_msg_close.3
/usr/share/man/man3/zmq_msg_copy.3
/usr/share/man/man3/zmq_msg_data.3
/usr/share/man/man3/zmq_msg_get.3
/usr/share/man/man3/zmq_msg_gets.3
/usr/share/man/man3/zmq_msg_init.3
/usr/share/man/man3/zmq_msg_init_buffer.3
/usr/share/man/man3/zmq_msg_init_data.3
/usr/share/man/man3/zmq_msg_init_size.3
/usr/share/man/man3/zmq_msg_more.3
/usr/share/man/man3/zmq_msg_move.3
/usr/share/man/man3/zmq_msg_recv.3
/usr/share/man/man3/zmq_msg_routing_id.3
/usr/share/man/man3/zmq_msg_send.3
/usr/share/man/man3/zmq_msg_set.3
/usr/share/man/man3/zmq_msg_set_routing_id.3
/usr/share/man/man3/zmq_msg_size.3
/usr/share/man/man3/zmq_poll.3
/usr/share/man/man3/zmq_poller.3
/usr/share/man/man3/zmq_ppoll.3
/usr/share/man/man3/zmq_proxy.3
/usr/share/man/man3/zmq_proxy_steerable.3
/usr/share/man/man3/zmq_recv.3
/usr/share/man/man3/zmq_recvmsg.3
/usr/share/man/man3/zmq_send.3
/usr/share/man/man3/zmq_send_const.3
/usr/share/man/man3/zmq_sendmsg.3
/usr/share/man/man3/zmq_setsockopt.3
/usr/share/man/man3/zmq_socket.3
/usr/share/man/man3/zmq_socket_monitor.3
/usr/share/man/man3/zmq_socket_monitor_versioned.3
/usr/share/man/man3/zmq_strerror.3
/usr/share/man/man3/zmq_timers.3
/usr/share/man/man3/zmq_unbind.3
/usr/share/man/man3/zmq_version.3
/usr/share/man/man3/zmq_z85_decode.3
/usr/share/man/man3/zmq_z85_encode.3

%files lib
%defattr(-,root,root,-)
/V3/usr/lib64/libzmq.so.5.2.5
/usr/lib64/libzmq.so.5
/usr/lib64/libzmq.so.5.2.5

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/libzmq/34f3af59f7997f370973f96fdc316677f47a813d
/usr/share/package-licenses/libzmq/82d0bcdf2087a772a9517374e2df993d85fb447e
/usr/share/package-licenses/libzmq/d22157abc0fc0b4ae96380c09528e23cf77290a9

%files man
%defattr(0644,root,root,0755)
/usr/share/man/man7/zmq.7
/usr/share/man/man7/zmq_curve.7
/usr/share/man/man7/zmq_gssapi.7
/usr/share/man/man7/zmq_inproc.7
/usr/share/man/man7/zmq_ipc.7
/usr/share/man/man7/zmq_null.7
/usr/share/man/man7/zmq_pgm.7
/usr/share/man/man7/zmq_plain.7
/usr/share/man/man7/zmq_tcp.7
/usr/share/man/man7/zmq_tipc.7
/usr/share/man/man7/zmq_udp.7
/usr/share/man/man7/zmq_vmci.7

%files staticdev
%defattr(-,root,root,-)
/usr/lib64/libzmq.a
